import { campaign } from '@/config/campaign'

export const galleryCategories = [
  'All',
  'T-Shirts',
  'Gifts',
  'Laser',
  'Stone',
  'LED/Neon',
  'Corporate',
] as const

export type GalleryCategory = (typeof galleryCategories)[number]

export type GalleryItem = {
  id: string
  category: Exclude<GalleryCategory, 'All'>
  label: string
  caption: string
  alt: string
  src: string
  aspect: 'portrait' | 'square' | 'landscape' | 'tall'
  kind: 'tee' | 'gift' | 'macro' | 'stone' | 'glow' | 'workshop'
}

export const galleryItems: GalleryItem[] = [
  {
    id: 'tee-bold',
    category: 'T-Shirts',
    label: 'Bold graphic',
    caption: 'Campaign photograph — a bold graphic on a black T-shirt.',
    alt: campaign.bold.alt,
    src: campaign.bold.src,
    aspect: 'portrait',
    kind: 'tee',
  },
  {
    id: 'tee-back',
    category: 'T-Shirts',
    label: 'Back print',
    caption: 'Campaign photograph — a graphic on the back of a T-shirt.',
    alt: campaign.backPrint.alt,
    src: campaign.backPrint.src,
    aspect: 'portrait',
    kind: 'tee',
  },
  {
    id: 'tee-type',
    category: 'T-Shirts',
    label: 'Lettering',
    caption: 'Campaign photograph — lettering on a white T-shirt.',
    alt: campaign.typography.alt,
    src: campaign.typography.src,
    aspect: 'square',
    kind: 'macro',
  },
  {
    id: 'tee-fashion',
    category: 'T-Shirts',
    label: 'Printed T-shirt',
    caption: 'Campaign photograph — a printed T-shirt, worn.',
    alt: campaign.fashion.alt,
    src: campaign.fashion.src,
    aspect: 'portrait',
    kind: 'tee',
  },
  {
    id: 'tee-black',
    category: 'T-Shirts',
    label: 'Black T-shirt',
    caption: 'Campaign photograph — black custom T-shirt.',
    alt: campaign.black.alt,
    src: campaign.black.src,
    aspect: 'tall',
    kind: 'tee',
  },
  {
    id: 'tee-white',
    category: 'T-Shirts',
    label: 'White T-shirt',
    caption: 'Campaign photograph — white T-shirt.',
    alt: campaign.white.alt,
    src: campaign.white.src,
    aspect: 'portrait',
    kind: 'tee',
  },
  {
    id: 'tee-fold',
    category: 'T-Shirts',
    label: 'Folded T-shirts',
    caption: 'Campaign photograph — folded T-shirts.',
    alt: campaign.folded.alt,
    src: campaign.folded.src,
    aspect: 'landscape',
    kind: 'workshop',
  },
  {
    id: 'tee-print',
    category: 'T-Shirts',
    label: 'Print close-up',
    caption: 'Campaign photograph — a printed mark.',
    alt: campaign.closeup.alt,
    src: campaign.closeup.src,
    aspect: 'square',
    kind: 'macro',
  },
  {
    id: 'tee-cricket',
    category: 'T-Shirts',
    label: 'Cricket jersey',
    caption: 'Campaign photograph — cricket apparel. Not a club kit.',
    alt: campaign.cricket.alt,
    src: campaign.cricket.src,
    aspect: 'portrait',
    kind: 'tee',
  },
  {
    id: 'tee-football',
    category: 'T-Shirts',
    label: 'Football jersey',
    caption: 'Campaign photograph — a custom football jersey. Not a club kit.',
    alt: campaign.footballFront.alt,
    src: campaign.footballFront.src,
    aspect: 'landscape',
    kind: 'tee',
  },
  {
    id: 'gift-a',
    category: 'Gifts',
    label: 'Gift',
    caption: 'Campaign photograph — a wrapped gift.',
    alt: campaign.gift.alt,
    src: campaign.gift.src,
    aspect: 'square',
    kind: 'gift',
  },
  {
    id: 'gift-b',
    category: 'Gifts',
    label: 'Gifts',
    caption: 'Campaign photograph — wrapped gifts.',
    alt: campaign.giftDetail.alt,
    src: campaign.giftDetail.src,
    aspect: 'portrait',
    kind: 'gift',
  },
  {
    id: 'laser-a',
    category: 'Laser',
    label: 'Objects',
    caption: 'Campaign photograph of objects. Not a photograph of BS CUSTOMS engraving.',
    alt: campaign.laser.alt,
    src: campaign.laser.src,
    aspect: 'landscape',
    kind: 'macro',
  },
  {
    id: 'stone-a',
    category: 'Stone',
    label: 'Ceramic pieces',
    caption: 'Campaign photograph of ceramic pieces. Not a photograph of BS CUSTOMS stone work.',
    alt: campaign.stone.alt,
    src: campaign.stone.src,
    aspect: 'portrait',
    kind: 'stone',
  },
  {
    id: 'led-a',
    category: 'LED/Neon',
    label: 'Neon sign',
    caption: 'Campaign photograph — hanging lights. Not a BS CUSTOMS sign.',
    alt: campaign.neon.alt,
    src: campaign.neon.src,
    aspect: 'landscape',
    kind: 'glow',
  },
  {
    id: 'corp-a',
    category: 'Corporate',
    label: 'Team apparel',
    caption: 'Campaign photograph — shirts prepared for a group. Not a client order.',
    alt: campaign.corporate.alt,
    src: campaign.corporate.src,
    aspect: 'landscape',
    kind: 'workshop',
  },
  {
    id: 'corp-b',
    category: 'Corporate',
    label: 'Colour stack',
    caption: 'Campaign photograph — folded shirts in several colours.',
    alt: campaign.stack.alt,
    src: campaign.stack.src,
    aspect: 'portrait',
    kind: 'workshop',
  },
]
